apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  type: ClusterIP
  ports:
  - name: echo-server
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: echo-server