apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-logger
  namespace: acme-kindred
spec:
  replicas: 1
  selector:
    matchLabels:
      app: json-logger
  template:
    metadata:
      labels:
        app: json-logger
    spec:
      containers:
        - name: json-logger
          image: json-logger:0.0.1