apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy
data:
  envoy.yaml: |-
    node:
      cluster: kindergarten
      id: kindergarten

    dynamic_resources:
      lds_config:
        resource_api_version: V3
        path: /etc/envoy/lds.yaml
      cds_config:
        resource_api_version: V3
        path: /etc/envoy/cds.yaml

    admin:
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901

